export const CITIES = {
    'banjaluka' : 'Banja Luka',
    'bileca' : 'Bileća',
    'bijeljina' : 'Bijeljina',
    'bogojno' : 'Bogojno',
    'bratunac' : 'Bratunac',
    'brcko' : 'Brčko',
    'buzim' : 'Bužim',
    'bihac' : 'Bihać',
    'bosanskakrupa' : 'Bosanska Krupa',
    'cacak' : 'Cacak',
    'capljina' : 'Čapljina',
    'cazin' : 'Cazin',
    'doboj' : 'Doboj',
    'foca' : 'Foča',
    'fojnica' : 'Fojnica',
    'gorazde' : 'Goražde',
    'gradacac' : 'Gradačac',
    'gradiska' : 'Gradiška',
    'hadzici' : 'Hadžići',
    'jajce' : 'Jajce',
    'kakanj' : 'Kakanj',
    'kalesija' : 'Kalesija',
    'kljuc' : 'Ključ',
    'kostajnica' : 'Kostajnica',
    'kotor_varos' : 'Kotor Varoš',
    'ljubinje' : 'Ljubinje',
    'ljubuski' : 'Ljubuški',
    'livno' : 'Livno',
    'mostar' : 'Mostar',
    'mogila' : 'Mogila',
    'neum' : 'Neum',
    'nevesinje' : 'Nevesinje',
    'novi_travnik' : 'Novi Travnik',
    'orasje' : 'Orašje',
    'ornes' : 'Orneš',
    'pale' : 'Pale',
    'prijedor' : 'Prijedor',
    'ribnik' : 'Ribnik',
    'samač' : 'Samač',
    'sanskimost' : 'Sanski Most',
    'sarajevo' : 'Sarajevo',
    'sipovo' : 'Sipovo',
    'sokolac' : 'Sokolac',
    'srebrenik' : 'Srebrenik',
    'srebrenica' : 'Srebrenica',
    'stolac' : 'Stolac',
    'teocak' : 'Teočak',
    'tesanj' : 'Tešanj',
    'tomislavgrad' : 'Tomislavgrad',
    'travnik' : 'Travnik',
    'trnovo' : 'Trnovo',
    'trebinje' : 'Trebinje',
    'usce' : 'Uskoplje',
    'valjevo' : 'Valjevo',
    'vares' : 'Vareš',
    'velika_kladusa' : 'Velika Kladuša',
    'vitez' : 'Vitez',
    'vogosca' : 'Vogošća',
    'zavidovici' : 'Zavidovići',
    'zenica' : 'Zenica',
    'zepce' : 'Žepče',
    'zeljeznopolje' : 'Željezno Polje',
    'zivinice' : 'Živinice',
}