const INITIAL_FORM_STATE = {

    imageUrls: [],
    name: '',
    description: '',
    city:'',
    address: '',
    type: 'rent',
    seats: 1,
    doors: 4,
    kW: 1,
    mileage: 1,
    regularPrice: 10,
    discountPrice: 0,
    offer: false,
    registered: false,
    airconditioner: false,
    model:'',
    brand:'',
    engine:'',
    year:'',
    capacity:'',
    transmission:'',
    wheeldrive:'',
    emission:'',
    cartype:'',
    interior:'',
    metallic: false,
    alloywheels: false,
    digitalairconditioning: false,
    steeringwheelcontrols: false,
    navigation: false,
    touchscreen: false,
    headupdisplay: false,
    usbport: false,
    cruisecontrol: false,
    bluetooth: false,
    carplay: false,
    rainsensor: false,
    parkassist: false,
    lightsensor: false,
    blindspotsensor: false,
    startstopsystem: false,
    hillassist: false,
    seatmemory: false,
    seatmassage: false,
    seatheating: false,
    seatcooling: false,
    powerwindows: false,
    powerseatadjustment: false,
    armrest: false,
    panoramicroof: false,
    sunroof: false,
    foglights: false,
    electricmirrors: false,
    alarm: false,
    centrallocking: false,
    remoteunlocking: false,
    airbag: false,
    abs: false,
    esp: false,
    dpffapfilter: false,
    powersteering: false,
    turbo: false,
    isofix: false,
    towbar: false,
    customscleared: false,
    foreignplates: false,
    leasing: false,
    servicebook: false,
    damaged: false,
    adaptedforthedisabled: false,
    oldtimer: false,
}

export default INITIAL_FORM_STATE