const RADIO_BUTTON_IDS = [
   'registered' ,
   'airconditioner' ,
   'offer' ,
   'metallic' ,
   'alloywheels' ,
   'digitalairconditioning' ,
   'steeringwheelcontrols' ,
   'navigation' ,
   'touchscreen' ,
   'headupdisplay' ,
   'usbport' ,
   'cruisecontrol' ,
   'bluetooth' ,
   'carplay' ,
   'rainsensor' ,
   'parkassist' ,
   'lightsensor' ,
   'blindspotsensor' ,
   'startstopsystem' ,
   'hillassist' ,
   'seatmemory' ,
   'seatmassage' ,
   'seatheating' ,
   'seatcooling' ,
   'powerwindows' ,
   'powerseatadjustment' ,
   'armrest' ,
   'panoramicroof' ,
   'sunroof' ,
   'foglights' ,
   'electricmirrors' ,
   'alarm' ,
   'centrallocking' ,
   'remoteunlocking' ,
   'airbag' ,
   'abs' ,
   'esp' ,
   'dpffapfilter' ,
   'powersteering' ,
   'turbo' ,
   'isofix' ,
   'towbar' ,
   'customscleared' ,
   'foreignplates' ,
   'leasing' ,
   'servicebook' ,
   'damaged' ,
   'adaptedforthedisabled' ,
   'oldtimer'
];

export default RADIO_BUTTON_IDS